/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Volt ADK. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { ISandboxPlan } from './sandboxPolicy.js';

/**
 * Linux: a tiny C helper Volt compiles on first use (no prebuilt binaries to ship or trust) that
 * applies Landlock and then execs the agent.
 *
 * - Writes: only below `--rw` paths (Landlock handles every write right the kernel's ABI knows;
 *   reads stay open, like Codex's full-read policies).
 * - Network (ABI 4+, Linux 6.7): TCP connects only to `--connect` ports (Volt's proxy and MCP
 *   server). Older kernels keep the network open and the helper says so on stderr.
 * - `--protect` / `--hide`: Landlock cannot carve a read-only hole inside a writable folder, so
 *   when unprivileged user namespaces are available the helper bind-mounts protected paths
 *   read-only (git hooks, configs) and hides secrets behind an empty tmpfs, as Codex does with
 *   bubblewrap. Without namespaces it carries on and warns.
 * - `--probe` prints the Landlock ABI (0 when the kernel has none).
 * A kernel without Landlock runs the agent unsandboxed with a warning, unless `--require`.
 */
export const LANDLOCK_HELPER_SOURCE = String.raw`/* Volt agent sandbox helper (Landlock). Generated by Volt; safe to delete. */
#define _GNU_SOURCE
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/syscall.h>
#include <unistd.h>

#ifndef __NR_landlock_create_ruleset
#define __NR_landlock_create_ruleset 444
#define __NR_landlock_add_rule 445
#define __NR_landlock_restrict_self 446
#endif

struct vl_ruleset_attr { uint64_t handled_access_fs; uint64_t handled_access_net; };
struct vl_path_beneath { uint64_t allowed_access; int32_t parent_fd; } __attribute__((packed));
struct vl_net_port { uint64_t allowed_access; uint64_t port; };

#define VL_VERSION (1U << 0)
#define VL_RULE_PATH 1
#define VL_RULE_NET 2
#define FS_WRITE_FILE (1ULL << 1)
#define FS_REMOVE_DIR (1ULL << 4)
#define FS_REMOVE_FILE (1ULL << 5)
#define FS_MAKE_CHAR (1ULL << 6)
#define FS_MAKE_DIR (1ULL << 7)
#define FS_MAKE_REG (1ULL << 8)
#define FS_MAKE_SOCK (1ULL << 9)
#define FS_MAKE_FIFO (1ULL << 10)
#define FS_MAKE_BLOCK (1ULL << 11)
#define FS_MAKE_SYM (1ULL << 12)
#define FS_REFER (1ULL << 13)
#define FS_TRUNCATE (1ULL << 14)
#define NET_CONNECT_TCP (1ULL << 1)

#define MAX_ITEMS 256

static int write_file(const char *path, const char *text) {
	int fd = open(path, O_WRONLY | O_CLOEXEC);
	if (fd < 0) return -1;
	ssize_t n = write(fd, text, strlen(text));
	close(fd);
	return n == (ssize_t)strlen(text) ? 0 : -1;
}

static unsigned long locked_flags(const char *path) {
	struct statvfs s;
	unsigned long flags = 0;
	if (statvfs(path, &s) != 0) return 0;
	if (s.f_flag & ST_NOSUID) flags |= MS_NOSUID;
	if (s.f_flag & ST_NODEV) flags |= MS_NODEV;
	if (s.f_flag & ST_NOEXEC) flags |= MS_NOEXEC;
	if (s.f_flag & ST_NOATIME) flags |= MS_NOATIME;
	if (s.f_flag & ST_RELATIME) flags |= MS_RELATIME;
	return flags;
}

/* Read-only binds and hidden secrets in a private mount namespace. Best effort. */
static void apply_mounts(char **protect, int nprotect, char **hide, int nhide) {
	if (!nprotect && !nhide) return;
	uid_t uid = getuid();
	gid_t gid = getgid();
	char map[64];
	if (unshare(CLONE_NEWUSER | CLONE_NEWNS) != 0) {
		fprintf(stderr, "volt-landlock: no user namespaces (%s); protected paths stay writable inside writable folders\n", strerror(errno));
		return;
	}
	write_file("/proc/self/setgroups", "deny");
	snprintf(map, sizeof map, "%u %u 1", (unsigned)uid, (unsigned)uid);
	write_file("/proc/self/uid_map", map);
	snprintf(map, sizeof map, "%u %u 1", (unsigned)gid, (unsigned)gid);
	write_file("/proc/self/gid_map", map);
	mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, NULL);
	for (int i = 0; i < nprotect; i++) {
		struct stat st;
		if (stat(protect[i], &st) != 0) continue;
		if (mount(protect[i], protect[i], NULL, MS_BIND | MS_REC, NULL) != 0 ||
			mount(NULL, protect[i], NULL, MS_BIND | MS_REMOUNT | MS_RDONLY | locked_flags(protect[i]), NULL) != 0) {
			fprintf(stderr, "volt-landlock: could not protect %s: %s\n", protect[i], strerror(errno));
		}
	}
	for (int i = 0; i < nhide; i++) {
		struct stat st;
		if (stat(hide[i], &st) != 0) continue;
		int rc = S_ISDIR(st.st_mode)
			? mount("tmpfs", hide[i], "tmpfs", MS_NOSUID | MS_NODEV, "size=4k,mode=000")
			: mount("/dev/null", hide[i], NULL, MS_BIND, NULL);
		if (rc != 0) fprintf(stderr, "volt-landlock: could not hide %s: %s\n", hide[i], strerror(errno));
	}
}

int main(int argc, char **argv) {
	char *rw[MAX_ITEMS], *protect[MAX_ITEMS], *hide[MAX_ITEMS];
	long ports[MAX_ITEMS];
	int nrw = 0, nprotect = 0, nhide = 0, nports = 0, restrict_net = 0, require = 0, probe = 0, i;
	for (i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "--")) { i++; break; }
		else if (!strcmp(argv[i], "--probe")) probe = 1;
		else if (!strcmp(argv[i], "--require")) require = 1;
		else if (!strcmp(argv[i], "--restrict-net")) restrict_net = 1;
		else if (i + 1 < argc && !strcmp(argv[i], "--rw") && nrw < MAX_ITEMS) rw[nrw++] = argv[++i];
		else if (i + 1 < argc && !strcmp(argv[i], "--protect") && nprotect < MAX_ITEMS) protect[nprotect++] = argv[++i];
		else if (i + 1 < argc && !strcmp(argv[i], "--hide") && nhide < MAX_ITEMS) hide[nhide++] = argv[++i];
		else if (i + 1 < argc && !strcmp(argv[i], "--connect") && nports < MAX_ITEMS) ports[nports++] = strtol(argv[++i], NULL, 10);
		else { fprintf(stderr, "volt-landlock: unknown argument %s\n", argv[i]); return 64; }
	}
	int abi = (int)syscall(__NR_landlock_create_ruleset, NULL, 0, VL_VERSION);
	if (abi < 0) abi = 0;
	if (probe) { printf("%d\n", abi); return 0; }
	if (i >= argc) { fprintf(stderr, "volt-landlock: no command\n"); return 64; }

	apply_mounts(protect, nprotect, hide, nhide);

	if (abi == 0) {
		if (require) { fprintf(stderr, "volt-landlock: this kernel has no Landlock\n"); return 78; }
		fprintf(stderr, "volt-landlock: this kernel has no Landlock; the agent runs WITHOUT the filesystem sandbox\n");
	} else {
		uint64_t fs = FS_WRITE_FILE | FS_REMOVE_DIR | FS_REMOVE_FILE | FS_MAKE_CHAR | FS_MAKE_DIR | FS_MAKE_REG | FS_MAKE_SOCK | FS_MAKE_FIFO | FS_MAKE_BLOCK | FS_MAKE_SYM;
		if (abi >= 2) fs |= FS_REFER;
		if (abi >= 3) fs |= FS_TRUNCATE;
		struct vl_ruleset_attr attr = { fs, (restrict_net && abi >= 4) ? NET_CONNECT_TCP : 0 };
		if (restrict_net && abi < 4) fprintf(stderr, "volt-landlock: Landlock ABI %d cannot limit network (needs Linux 6.7); network stays open\n", abi);
		int ruleset = (int)syscall(__NR_landlock_create_ruleset, &attr, sizeof attr, 0);
		if (ruleset < 0) { perror("volt-landlock: landlock_create_ruleset"); if (require) return 78; }
		else {
			for (int r = 0; r < nrw; r++) {
				int fd = open(rw[r], O_PATH | O_CLOEXEC);
				if (fd < 0) continue;
				struct stat st;
				struct vl_path_beneath rule = { fs, fd };
				if (fstat(fd, &st) == 0 && !S_ISDIR(st.st_mode)) rule.allowed_access = fs & (FS_WRITE_FILE | FS_TRUNCATE);
				if (syscall(__NR_landlock_add_rule, ruleset, VL_RULE_PATH, &rule, 0) != 0) fprintf(stderr, "volt-landlock: rule for %s: %s\n", rw[r], strerror(errno));
				close(fd);
			}
			if (attr.handled_access_net) {
				for (int p = 0; p < nports; p++) {
					struct vl_net_port rule = { NET_CONNECT_TCP, (uint64_t)ports[p] };
					syscall(__NR_landlock_add_rule, ruleset, VL_RULE_NET, &rule, 0);
				}
			}
			if (prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) != 0 || syscall(__NR_landlock_restrict_self, ruleset, 0) != 0) {
				perror("volt-landlock: landlock_restrict_self");
				if (require) return 78;
			}
			close(ruleset);
		}
	}
	execvp(argv[i], &argv[i]);
	fprintf(stderr, "volt-landlock: %s: %s\n", argv[i], strerror(errno));
	return 127;
}
`;

/** Arguments for the helper: everything before `--`. */
export function landlockArgs(plan: ISandboxPlan, connectPorts: readonly number[]): string[] {
	const args: string[] = [];
	for (const path of [...plan.writableSubpaths, ...plan.writableFiles, '/dev', '/proc']) {
		args.push('--rw', path);
	}
	for (const path of [...plan.denyWriteSubpaths, ...plan.denyWriteFiles]) {
		args.push('--protect', path);
	}
	for (const path of plan.denyReadSubpaths) {
		args.push('--hide', path);
	}
	if (plan.network === 'proxy') {
		args.push('--restrict-net');
		for (const port of connectPorts) {
			args.push('--connect', String(port));
		}
	}
	return args;
}

/** bubblewrap, when present and no compiler is: writes limited the same way; no network filtering. */
export function bwrapArgs(plan: ISandboxPlan): string[] {
	const args = ['--ro-bind', '/', '/', '--dev', '/dev', '--proc', '/proc', '--die-with-parent'];
	for (const path of [...plan.writableSubpaths, ...plan.writableFiles]) {
		args.push('--bind-try', path, path);
	}
	for (const path of [...plan.denyWriteSubpaths, ...plan.denyWriteFiles]) {
		args.push('--ro-bind-try', path, path);
	}
	for (const path of plan.denyReadSubpaths) {
		args.push('--tmpfs', path);
	}
	return args;
}
