name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install

      - name: Build Turbo
        run: bun run build

      - name: Build/Release Electron app (macOS)
        if: startsWith(matrix.os, 'macos')
        run: bun --cwd apps/desktop run package:mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_HARD_LINKS: false

      - name: Build/Release Electron app (Windows)
        if: startsWith(matrix.os, 'windows')
        run: bun --cwd apps/desktop run package:win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Snapcraft (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo snap install snapcraft --classic

      - name: Build/Release Electron app (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: bun --cwd apps/desktop run package:linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
